### ISSUE TITLE
Digital Download Spring Filmstock

### ISSUE THREAD

**Issue by JoseRivas1998** [JoseRivas1998/SSHS-Redesign#195]
## Internal or External Request

External
## If External, enter who submitted the request

Mr. Golden
## Describe the request

Mr. Golden would like to be able to distribute Filmstock digitally instead of by making physical dvd's. It would be best to research this and figure it out before Spring Filmstock
## Proposed Due Date

4-31-16

**Comment by JoseRivas1998** [comment]
Switching to standard priority because of approaching due date.

**Comment by JoseRivas1998** [comment]
Either Hunter or Guillermo are going to come in from CTE Video during 7th Period to talk to @socinian about this

**Comment by JoseRivas1998** [comment]
Switching to High Priority due to Golden needing to figure this out ASAP

**Comment by JoseRivas1998** [comment]
Where are we on this @socinian ? Filmstock is **NEXT SATURDAY**

**Comment by JoseRivas1998** [comment]
Can this be closed?

**Comment by socinian** [comment]
Closing.
