### ISSUE TITLE
oldsite.santasusana.org Broken

### ISSUE THREAD

**Issue by JoseRivas1998** [JoseRivas1998/SSHS-Redesign#213]
## Internal or External Request

Internal
## Describe the request

Trying to access http://oldsite.santasusana.org/ returns ERR_NAME_NOT_RESOLVED. I added all the missing from my local backup, but I am still getting the same error.
## Proposed Due Date

3-31-16
## Relevant Screenshots

![image](https://cloud.githubusercontent.com/assets/6099936/13370398/ef06810a-dcba-11e5-8645-db066b36a6e1.png)

**Comment by JoseRivas1998** [comment]
Switching to high priority because I want to be able to link to the old site on the current site

**Comment by socinian** [comment]
I deleted the server since Mr. Torti had express the desire to make a clean break and not risk confusing other when/if the content is different between the two. Someone might want to make an issue saying we promised one thing on the old site when the reality is something else on the updated site.

**Comment by JoseRivas1998** [comment]
All right, I'll just close the issue then
