### ISSUE TITLE
Correct Ratio for Carousel on Large Screens

### ISSUE THREAD

**Issue by socinian** [JoseRivas1998/SSHS-Redesign#299]
## Internal or External Request

External 
## Who submitted the request

Mr. Abby
#### If external, it would be best to simply paste the request below

On extra wide browser views of the homepage, the carousel images start to distort in order to keep to the width of the screen. When the high stops growing, the width should stop growing, to keep image aspect ratio.

Per Mr. Abbe:
"Is there a way to fix the images on the main page of the website? They skew disproportionately. Thank you.

"Please let Jose know that it's not professional to allow images to rescale disproportionately. Yes, it's only noticeable on wide screen browsers which most people have these days.  "
## Proposed Due Date

As soon as practical. 
## Relevant Screenshots

![image](https://cloud.githubusercontent.com/assets/1112767/14824177/db4668f8-0b89-11e6-8f52-19bdd128eb26.png)

**Comment by JoseRivas1998** [comment]
I was instructed by Torti to not allow the images to be too big on larger screens, so I had to reduce the height.

**Comment by JoseRivas1998** [comment]
And the width is fixed to the size of the screen

**Comment by JoseRivas1998** [comment]
Updated the title because the original title was way too long

**Comment by JoseRivas1998** [comment]
Fixed by adding a media query in the css that makes the carousel take up less of the screen at a break point
