### ISSUE TITLE
Replace Senior Newsletter 2015 with 2016

### ISSUE THREAD

**Issue by socinian** [JoseRivas1998/SSHS-Redesign#305]
## Internal or External Request

External
## If External, enter who submitted the request

Jill Brown
## Describe the request

On the "Senior Only" page https://www.santasusana.org/students/seniorsonly.php

Replace the link and link text from **Class of 2015 Senior Newsletter** to **Class of 2016 Senior Newsletter**
Which points to this document where it has been uploaded to resources:
https://drive.google.com/open?id=0B62lI1yotpAcNm5GNkFaaG5VcmpFdTJRMkpPT3FqM0pIQ2RV
## Proposed Due Date

5/13/16

**Comment by JoseRivas1998** [comment]
[Senior Newsletter 2016.pdf](https://github.com/Santa-Susana-High-School/SSHS-Redesign/files/261892/Senior.Newsletter.2016.pdf)

**Comment by JoseRivas1998** [comment]
Done 15 minutes
